name: API Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: node run-tests.js

      - name: Prepare PR-specific report folder
        run: |
          mkdir -p ./reports/pr-${{ github.event.pull_request.number }}
          shopt -s extglob
          mv ./reports/!(pr-${{ github.event.pull_request.number }}) ./reports/pr-${{ github.event.pull_request.number }}/ || true

      - name: Upload PR test reports
        uses: actions/upload-artifact@v3
        with:
          name: "API Test Reports - PR #${{ github.event.pull_request.number }}"
          path: ./reports
