name: API Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: node run-tests.js

      - name: Prepare PR-specific report folder
        run: |
          mkdir -p ./reports/pr-${{ github.event.pull_request.number }}
          mv ./reports/* ./reports/pr-${{ github.event.pull_request.number }}/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload test reports
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./reports

      - name: Deploy test reports
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact: ./reports

      - name: Add report link to PR summary
        if: always()
        run: |
          echo "📄 [View API Test Reports for PR #${{ github.event.pull_request.number }}](${{ steps.deployment.outputs.page_url }}/pr-${{ github.event.pull_request.number }}/index.html)" >> $GITHUB_STEP_SUMMARY
