name: API Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: node run-tests.js

      - name: Deploy test reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
          destination_dir: pr-${{ github.event.pull_request.number }}
          force_orphan: false   # keep history of previous PR reports

      - name: Add report link to PR summary
        if: always()
        run: |
          echo "📄 [View API Test Reports](https://${{ github.repository_owner }}.github.io/${{ github.repository }}/pr-${{ github.event.pull_request.number }}/index.html)" >> $GITHUB_STEP_SUMMARY
